# Your Website Title
title: Zhihan Liao

# Your Website URL
url: 'http://liao-zhihan.github.io'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: Zhihan Liao
tagline: Software Engineer, SLAM
pic: profile.png # profile.png can be found at /assets/images/profile.png
description: love coding, love life
description_tiny: 'Home: +60-4 | Studied: +1-408 | Work: +60-3'
email: 499174318@qq.com
website: liao-zhihan.github.io # do not add http://
linkedin: 
github: liao-zhihan
twitter: '@realmelvinchng'

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm
